version: "3.9"

services:
  neo4j:
    image: neo4j:5.12.0
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/testpassword   # username/password
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
    ports:
      - "7474:7474"  # HTTP Browser
      - "7687:7687"  # Bolt Protocol
    volumes:
      - neo4j-data:/data
      - neo4j-import:/import
      - neo4j-logs:/logs
    restart: unless-stopped

volumes:
  neo4j-data:
  neo4j-import:
  neo4j-logs:
