# Dockerfile FOR Rancher
FROM rancher/rancher:latest

LABEL maintainer="Your Name <you@example.com>"
LABEL description="Rancher management platform"

VOLUME ["/var/lib/rancher"]

# command RUN
CMD ["/usr/bin/entry"]
