# Use official SonarQube Community Edition image
FROM sonarqube:community

# Maintainer info
LABEL maintainer="yourname@example.com"

# پورت پیشفرض وب UI SonarQube
EXPOSE 9000

# تنظیمات اختیاری ENV
# ENV SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
# ENV SONAR_JDBC_USERNAME=sonar
# ENV SONAR_JDBC_PASSWORD=sonar

# دستور پیشفرض image خودش رو اجرا می‌کنه، نیازی به CMD نیست
