version: "3.9"

services:
  memcached:
    build:
      context: ./memcached
      dockerfile: Dockerfile
    image: custom-memcached:latest
    container_name: my_memcached
    restart: unless-stopped
    ports:
      - "11211:11211"
    command: memcached -m 128 -o modern -v
