version: "3.9"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: sqlite3       # or mysql/postgres
      GITEA__database__PATH: /data/gitea.db  # used for SQLite
    ports:
      - "3000:3000"   # Web UI
      - "2222:22"     # SSH for Git
    volumes:
      - gitea_data:/data

volumes:
  gitea_data:
