# Dockerfile برای Keycloak
FROM quay.io/keycloak/keycloak:21.1.1

LABEL maintainer="Your Name <you@example.com>"
LABEL description="Keycloak IAM Server"

# Volume برای ذخیره داده‌ها
VOLUME ["/opt/keycloak/data"]

# فرمان اجرا (به صورت development mode)
CMD ["start-dev"]
