version: "3.9"

services:
  mailpit:
    build:
      context: ./mailpit
      dockerfile: Dockerfile
    image: custom-mailpit:latest
    container_name: my_mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
