# Use official pgAdmin image
FROM dpage/pgadmin4:latest

# Maintainer info
LABEL maintainer="yourname@example.com"
LABEL description="pgAdmin for managing PostgreSQL databases"

# Default port
EXPOSE 80

# Optional environment variables
# ENV PGADMIN_DEFAULT_EMAIL=admin@example.com
# ENV PGADMIN_DEFAULT_PASSWORD=admin

# pgAdmin runs automatically, no CMD needed
