version: "3.9"

services:
  gitlab:
    build:
      context: ./gitlab   # folder containing your Dockerfile
      dockerfile: Dockerfile
    image: custom-gitlab-ce:latest
    container_name: gitlab
    restart: unless-stopped
    hostname: gitlab.local
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.local'
        gitlab_rails['gitlab_shell_ssh_port']=2224
    ports:
      - "80:80"       # HTTP
      - "443:443"     # HTTPS
      - "2224:22"     # SSH for Git
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
