# Dockerfile برای Mongo Express
FROM mongo-express:latest

LABEL maintainer="Your Name <you@example.com>"
LABEL description="Mongo Express container for managing MongoDB databases"

# Volume برای ذخیره تنظیمات (اختیاری)
VOLUME ["/config"]

# فرمان اجرا
CMD ["npm", "start"]
