version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: my_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    build:
      context: ./mongo-express   # folder containing your Dockerfile
      dockerfile: Dockerfile
    image: custom-mongo-express:latest
    container_name: my_mongo_express
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_SERVER: mongo
    volumes:
      - ./mongo-express/config:/config   # optional mount for custom config

volumes:
  mongo_data:
