version: "3.9"
services:
  vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    container_name: vault_service
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK   # prevents Vault from swapping to disk
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
    volumes:
      - vault_data:/vault/data
    restart: unless-stopped

volumes:
  vault_data:
    driver: local
