version: "3.9"

services:
  cadvisor:
    build:
      context: ./cadvisor
      dockerfile: Dockerfile
    image: custom-cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro   # access Docker metrics
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
