# Dockerfile برای Portainer
FROM portainer/portainer-ce:latest

LABEL maintainer="Your Name <you@example.com>"
LABEL description="Portainer CE for managing Docker containers"

# Volume برای ذخیره تنظیمات
VOLUME ["/data"]

# فرمان اجرا
CMD ["--no-analytics"]
