# Use the official Portainer CE image
FROM portainer/portainer-ce:latest

# Maintainer and description
LABEL maintainer="Your Name <you@example.com>"
LABEL description="Portainer CE for managing Docker containers"

# Volume to persist Portainer data
VOLUME ["/data"]

# Run Portainer with no analytics
CMD ["--no-analytics"]
