version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"  # Web UI
      - "9443:9443"  # HTTPS (optional)
    volumes:
      - portainer_data:/data  # Persistent data for Portainer
      - /var/run/docker.sock:/var/run/docker.sock  # Access to Docker host

volumes:
  portainer_data:
