# Dockerfile برای MinIO
FROM minio/minio:latest

LABEL maintainer="Your Name <you@example.com>"
LABEL description="MinIO Object Storage"

# مسیر داده‌ها
VOLUME ["/data"]

# فرمان اجرا
CMD ["server", "/data"]
