# Dockerfile برای RedisInsight
FROM redislabs/redisinsight:latest

LABEL maintainer="Your Name <you@example.com>"
LABEL description="RedisInsight container for managing Redis databases"

# Volume برای ذخیره تنظیمات
VOLUME ["/db"]

# فرمان اجرا
CMD ["/entrypoint.sh"]
