version: "3.9"

services:
  phpnginx:
    build:
      context: ./phpnginx  # Path to the Dockerfile
      dockerfile: Dockerfile
    container_name: phpnginx
    restart: unless-stopped
    ports:
      - "8080:80"          # Map container port 80 to host port 8080
    volumes:
      - ./phpnginx/www:/var/www/html  # Your PHP application files
      - ./phpnginx/config/nginx.conf:/etc/nginx/conf.d/default.conf  # Optional custom nginx config
    environment:
      PHP_DISPLAY_ERRORS: "1"
      PHP_MEMORY_LIMIT: "512M"
