version: "3.9"

services:
  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    image: custom-mongo:latest
    container_name: my_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: my_database
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
