version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - REDIS_INSIGHT_NO_ANALYTICS=true

volumes:
  redis_data:
